"""Change MilvusConnection model v2

Revision ID: 1e8483238d41
Revises: d8ee478a8d64
Create Date: 2025-09-12 16:01:57.904944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8483238d41'
down_revision: Union[str, Sequence[str], None] = 'd8ee478a8d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milvus_connections', 'host',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment="Milvus 服务器完整地址，包含协议和端口，如 'http://localhost:19530' 或 'https://milvus.example.com:19530'",
               existing_comment="Milvus 服务器主机地址，如 'localhost' 或 'milvus.example.com'",
               existing_nullable=False)
    op.alter_column('milvus_connections', 'database_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Milvus 数据库名称（必填）',
               existing_comment='Milvus 数据库名称，可选（Milvus 2.0+ 支持多数据库）')
    op.alter_column('milvus_connections', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment='Milvus 认证用户名（必填，明文存储，传输时加密保护）',
               existing_comment='Milvus 认证用户名（明文存储，传输时加密保护）')
    op.alter_column('milvus_connections', 'encrypted_password',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='使用 AES 对称加密存储的密码（必填）',
               existing_comment='使用 AES 对称加密存储的密码（如果启用了认证）')
    op.drop_column('milvus_connections', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('port', sa.INTEGER(), server_default=sa.text('19530'), autoincrement=False, nullable=False, comment='Milvus 服务器端口，默认 19530'))
    op.alter_column('milvus_connections', 'encrypted_password',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='使用 AES 对称加密存储的密码（如果启用了认证）',
               existing_comment='使用 AES 对称加密存储的密码（必填）')
    op.alter_column('milvus_connections', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Milvus 认证用户名（明文存储，传输时加密保护）',
               existing_comment='Milvus 认证用户名（必填，明文存储，传输时加密保护）')
    op.alter_column('milvus_connections', 'database_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Milvus 数据库名称，可选（Milvus 2.0+ 支持多数据库）',
               existing_comment='Milvus 数据库名称（必填）')
    op.alter_column('milvus_connections', 'host',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               comment="Milvus 服务器主机地址，如 'localhost' 或 'milvus.example.com'",
               existing_comment="Milvus 服务器完整地址，包含协议和端口，如 'http://localhost:19530' 或 'https://milvus.example.com:19530'",
               existing_nullable=False)
    # ### end Alembic commands ###
