"""Change milvus_connections

Revision ID: 3bca42321089
Revises: 86463602f88e
Create Date: 2025-09-15 13:30:42.274379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bca42321089'
down_revision: Union[str, Sequence[str], None] = '86463602f88e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('uri', sa.String(length=500), nullable=False, comment="Milvus 连接 URI，完整地址包含协议和端口，如 'http://localhost:19530' 或 'https://cluster.vectordb.zillizcloud.com'"))
    op.add_column('milvus_connections', sa.Column('encrypted_token', sa.Text(), nullable=False, comment='使用 AES 对称加密存储的认证 token（必填，格式：token 或 username:password）'))
    op.drop_column('milvus_connections', 'username')
    op.drop_column('milvus_connections', 'host')
    op.drop_column('milvus_connections', 'encrypted_password')
    op.drop_column('milvus_connections', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('port', sa.INTEGER(), server_default=sa.text('19530'), autoincrement=False, nullable=False, comment='Milvus 服务器端口，默认 19530'))
    op.add_column('milvus_connections', sa.Column('encrypted_password', sa.TEXT(), autoincrement=False, nullable=False, comment='使用 AES 对称加密存储的密码（必填）'))
    op.add_column('milvus_connections', sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment="Milvus 服务器主机地址，如 'localhost', '192.168.1.100' 或 'http://example.com'"))
    op.add_column('milvus_connections', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Milvus 认证用户名（必填，明文存储，传输时加密保护）'))
    op.drop_column('milvus_connections', 'encrypted_token')
    op.drop_column('milvus_connections', 'uri')
    # ### end Alembic commands ###
