"""Change MilvusConnection model v3

Revision ID: 86463602f88e
Revises: 1e8483238d41
Create Date: 2025-09-12 16:06:33.964820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86463602f88e'
down_revision: Union[str, Sequence[str], None] = '1e8483238d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('port', sa.Integer(), server_default='19530', nullable=False, comment='Milvus 服务器端口，默认 19530'))
    op.alter_column('milvus_connections', 'host',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               comment="Milvus 服务器主机地址，如 'localhost', '192.168.1.100' 或 'http://example.com'",
               existing_comment="Milvus 服务器完整地址，包含协议和端口，如 'http://localhost:19530' 或 'https://milvus.example.com:19530'",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('milvus_connections', 'host',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               comment="Milvus 服务器完整地址，包含协议和端口，如 'http://localhost:19530' 或 'https://milvus.example.com:19530'",
               existing_comment="Milvus 服务器主机地址，如 'localhost', '192.168.1.100' 或 'http://example.com'",
               existing_nullable=False)
    op.drop_column('milvus_connections', 'port')
    # ### end Alembic commands ###
