"""Add api-key test data

Revision ID: b80e0fb26428
Revises: 60fcbb3ded14
Create Date: 2025-09-09 20:04:04.344106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80e0fb26428'
down_revision: Union[str, Sequence[str], None] = '60fcbb3ded14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True, comment='最后一次测试该 API Key 的时间'))
    op.add_column('api_keys', sa.Column('test_status', sa.String(length=20), nullable=True, comment='最后一次测试状态：success(成功) 或 failed(失败)'))
    op.add_column('api_keys', sa.Column('test_message', sa.String(length=500), nullable=True, comment='最后一次测试的详细信息或错误消息'))
    op.add_column('api_keys', sa.Column('test_response_time', sa.Float(), nullable=True, comment='最后一次测试的响应时间（毫秒）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'test_response_time')
    op.drop_column('api_keys', 'test_message')
    op.drop_column('api_keys', 'test_status')
    op.drop_column('api_keys', 'last_tested_at')
    # ### end Alembic commands ###
