"""Change MilvusConnection model

Revision ID: d8ee478a8d64
Revises: eb3d5841f1f9
Create Date: 2025-09-12 15:37:39.964219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ee478a8d64'
down_revision: Union[str, Sequence[str], None] = 'eb3d5841f1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('username', sa.String(length=255), nullable=True, comment='Milvus 认证用户名（明文存储，传输时加密保护）'))
    op.drop_column('milvus_connections', 'encrypted_username')
    op.drop_column('milvus_connections', 'username_preview')
    op.drop_column('milvus_connections', 'secure')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milvus_connections', sa.Column('secure', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否使用 TLS/SSL 安全连接'))
    op.add_column('milvus_connections', sa.Column('username_preview', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment="用户名的安全预览格式，如 'admin****'"))
    op.add_column('milvus_connections', sa.Column('encrypted_username', sa.TEXT(), autoincrement=False, nullable=True, comment='使用 AES 对称加密存储的用户名（如果启用了认证）'))
    op.drop_column('milvus_connections', 'username')
    # ### end Alembic commands ###
